// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC13LdlwFFF_xU0QIEJbF8Qni6X0euUaM',
    appId: '1:990361566789:web:web_app_id',
    messagingSenderId: '990361566789',
    projectId: 'comunity-74ad2',
    authDomain: 'comunity-74ad2.firebaseapp.com',
    storageBucket: 'comunity-74ad2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC13LdlwFFF_xU0QIEJbF8Qni6X0euUaM',
    appId: '1:990361566789:android:android_app_id',
    messagingSenderId: '990361566789',
    projectId: 'comunity-74ad2',
    storageBucket: 'comunity-74ad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC13LdlwFFF_xU0QIEJbF8Qni6X0euUaM',
    appId: '1:990361566789:ios:6e6cd3c1a45aa95016ed2c',
    messagingSenderId: '990361566789',
    projectId: 'comunity-74ad2',
    storageBucket: 'comunity-74ad2.firebasestorage.app',
    iosClientId: '990361566789-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventosComunidad',
  );
}
